---
- hosts: windows
  gather_facts: no
  connection: local
  tasks:
    - name: Install AD-Domain-Services feature
      win_feature: 
        name: AD-Domain-Services
        include_management_tools: yes
        include_sub_features: yes
        state: present
    - name: Promote to domain controller
      win_domain_controller: 
        dns_domain_name: ansible.com
        domain_admin_user: admin@ansible.com
        domain_admin_password: Server12345!
        safe_mode_password: Server12345!
        state: domain_controller
        log_path: C:\ansible_win_domain_controller.txt
      register: result

    - name: Reboot upon promotion
      raw: shutdown /r
      when: result|changed
      async: 0
      poll: 0
      ignore_errors: true

