---
- hosts: windows2
  gather_facts: no
  tasks:
    - name: add to domain
      win_domain_membership:
        dns_domain_name: ansible.com
        hostname: EC2AMAZ-PQT2BCA
        domain_admin_user: admin@ansible.com
        domain_admin_password: password@123
        domain_ou_path: "OU=Windows,OU=Servers,DC=ansible,DC=com"
        state: domain
      register: domain_state
    - win_reboot:
      when: domain_state.reboot_required
