---
- hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
    - name: launch instance
      ec2:
        key_name: "{{ keypair }}"
        group: default
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
      register: ec2
    - name: print all ec2 variables
      debug: var=ec2
