---
- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    keypair: New_key
    instance_type: t2.micro
    image: ami-0f65671a86f061fcd
    region: us-east-2
  tasks:
    - name: launch instance
      ec2:
        key_name: "{{ keypair }}"
        group: default
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
      register: ec2
    - name: print all ec2 variables
      debug: var=ec2
