---
- hosts: windows1
  connection: local
  gather_facts: yes
  tasks:
    - name: fetch file
      fetch:
        src: C:\logfile.csv
        dest: /root/ansible/logfile_{{ ansible_env.COMPUTERNAME }}
        flat: yes
