---
- hosts: windows2
  gather_facts: no
  tasks:
    - name:  domain controller
      win_domain_controller:
        dns_domain_name: ansible.com
        domain_admin_user: admin@ansible.com
        domain_admin_password: password@123
        safe_mode_password: password@123
        domain_ou_path: "OU=Windows,OU=Servers,DC=ansible,DC=com"
        state: domain_controller
        log_path: C:\ansible_win_domain_controller.txt
      register: domain_state

