- hosts: 52.15.144.229
  gather_facts: false
  tasks:
    - name: Get the win password
      ec2_win_password:
        profile: dev
        instance_id: i-0fa0cd7fcafa1a543
        region: us-east-2
        key_file: "~/.ssh/aws.pem"
        wait: yes
        wait_timeout: 120

